### ISSUE TITLE
Kalman .update throwing type error with 'allow_singular' argument with scipy 0.14

### ISSUE THREAD

**Issue by David-Herman** [rlabbe/filterpy#55]
Hello,

I am working with python 2.7 on Windows 64 bit. I have scipy  0.14, filterpy 0.14, and numpy 1.11.1 installed.

As expected, in 0.14 Scipy, there is no 'allow_singular' keyword.

https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.multivariate_normal.html
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-4fb5edfe00d6> in <module>()
     88                 filt_AngularVelocity.append(kalman['ang'].predict)
     89                 print image_center[-1][0]
---> 90                 kalman['x'].update(float(image_center[-1][0]))
     91                 kalman['y'].update(float(image_center[-1][1]))
     92                 kalman['ang'].update(AngularVelocity[-1])

C:\Python27\lib\site-packages\filterpy\kalman\kalman_filter.pyc in update(self, z, R, H)
    203         flatz = np.asarray(z).flatten()
    204         self.log_likelihood = multivariate_normal.logpdf(
--> 205              flatz, mean, cov=S, allow_singular=True)
    206 
    207 

TypeError: logpdf() got an unexpected keyword argument 'allow_singular'

**Comment by takgr** [comment]
I've got the same problem on a clean installation of Debian 8 Linux.

  File "/usr/local/lib/python2.7/dist-packages/filterpy/kalman/kalman_filter.py", line 205, in update
    flatz, mean, cov=S, allow_singular=True)
TypeError: logpdf() got an unexpected keyword argument 'allow_singular'

**Comment by rlabbe** [comment]
I've worked around this by adding a function logpdf() to filterpy.stats. It tests to see if this keyword is supported, and does not use it if not. It also helps simplify the KF code as it will flatten the input parameters for you, so you will no longer see flatz in kalman_filter.py, for example.

Of course, this means that if the system covariance (S) is singular or not PSD you will now get an exception. This will typically occur when the measurement noise is low to none, as you no longer have uncertainty in the normal to the measurement hyperplane. 

Changes are pushed to version 0.1.5, released today.
